AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: m3.large
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - c1.medium
      - c1.xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - g2.2xlarge
      - g2.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - cr1.8xlarge
      - cc2.8xlarge
      - cg1.4xlarge
    Description: Enter instance size. Default is m3.large.
  AMI:
    Type: String
    Default: ami-034e1d78dd9d4a332
    Description: AMI Image
  IPAddress:
    Type: String
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open RDP, HTTP and Octopus listening tentacles
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: !Join
            - ''
            - - !Ref IPAddress
              - '/32'
  Windows:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: InstanceTypeParameter
      KeyName: DukeLegion
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/mcasperson/OctopusSandbox/master/install.ps1'))
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-WebServerRole
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-WebServer
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-CommonHttpFeatures
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-HttpErrors
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-HttpRedirect
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-ApplicationDevelopment
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-NetFxExtensibility45
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-HealthAndDiagnostics
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-HttpLogging
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-LoggingLibraries
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-RequestMonitor
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-HttpTracing
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-Security
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-RequestFiltering
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-Performance
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-WebServerManagementTools
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-IIS6ManagementCompatibility
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-Metabase
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-ManagementConsole
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-BasicAuthentication
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-WindowsAuthentication
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-StaticContent
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-DefaultDocument
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-WebSockets
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-ApplicationInit
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-NetFxExtensibility45
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-ASPNET45
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-ISAPIExtensions
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-ISAPIFilter
          Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName IIS-HttpCompressionStatic
          </powershell>
      Tags:
        -
          Key: Appplication
          Value:  Windows Server 2016
        -
          Key: Domain
          Value: None
        -
          Key: Environment
          Value: Test
        -
          Key: LifeTime
          Value: Transient
        -
          Key: Name
          Value:  Windows Server 2016
        -
          Key: OS
          Value: Windows
        -
          Key: OwnerContact
          Value: "#{Deployer Contact}"
        -
          Key: Purpose
          Value: Support Test Instance
        -
          Key: Source
          Value: CloudForation Script in Octopus Deploy
        -
          Key: scheduler:ec2-startstop
          Value: true
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - Windows
        - PublicIp
    Description: Server's PublicIp Address